#pragma once

const float GRID_SIZE = 32.0f;
const float FRAMES_PER_SECOND = 60.0f;
const int SCREEN_WIDTH_CELLS = 50; // 50 * 32 = 1600
const int SCREEN_HEIGHT_CELLS = 30; // 30 * 32 = 960
const int SCREEN_WIDTH = SCREEN_WIDTH_CELLS * GRID_SIZE;
const int SCREEN_HEIGHT = SCREEN_HEIGHT_CELLS * GRID_SIZE;
const int INVENTORY_WIDTH_CELLS = 10;
const int INVENTORY_HEIGHT_CELLS = 10;
const int INVENTORY_WIDTH = INVENTORY_WIDTH_CELLS * GRID_SIZE;
const int INVENTORY_HEIGHT = INVENTORY_HEIGHT_CELLS * GRID_SIZE;
const int INVENTORY_PADDING_CELLS = 1;
const int INVENTORY_PADDING = INVENTORY_PADDING_CELLS * GRID_SIZE;
const int INVENTORY_H_MARGIN_CELLS = (SCREEN_WIDTH_CELLS - INVENTORY_WIDTH_CELLS * 2 - INVENTORY_PADDING_CELLS * 3) / 2;
const int INVENTORY_H_MARGIN = INVENTORY_H_MARGIN_CELLS * GRID_SIZE;
const int INVENTORY_V_MARGIN_CELLS = (SCREEN_HEIGHT_CELLS - INVENTORY_HEIGHT_CELLS - INVENTORY_PADDING_CELLS * 2) / 2;
const int INVENTORY_V_MARGIN = INVENTORY_V_MARGIN_CELLS * GRID_SIZE;
